LINUXCN-18 Update to Debian 11 LXD 5
joyent/linux-live pull request #18
Opened 2023-05-17 15:32 UTC by travispaul

Update to Debian 11 and LXD 5.0.1 (latest LTS) 

Tested locally also confirmed that a container created with LXD v4 will still work with LXD v5 after a PI upgrade.

Depends on TritonDataCenter/sdc-headnode/pull/78

2023-06-28 19:17 UTC, travispaul commented
Engcall notes:
- Make sure any pinned packages are pulling from Deb 11 repositories
- Get LINUXCN-19 agent changes merged into master, update agent installation here to be from master

2023-08-22 12:32 UTC, danmcd approved these changes

2023-08-24 02:16 UTC, bahamat requested changes

2023-08-24 02:16 UTC, bahamat commented on tools/debian-live
> +	    git -C /usr/triton/defaults/agents clone -b LINUXCN-19 https://github.com/TritonDataCenter/sdc-cn-agent cn-agent
This will need to be put back to the linuxcn branch.

It might be a good idea to be able to read the branch from an envvar or cli arg.

2023-08-24 02:16 UTC, bahamat commented on tools/debian-live
>  zfs_ver=2.0.4
Might as well see about bumping rust and zfs also.

2023-08-24 02:16 UTC, bahamat commented on tools/debian-live
> +    sharutils
What's this for?

2023-08-24 02:16 UTC, bahamat commented on docs/6-quick-start.md
> +
I'm not comfortable with this. Requiring this for each CN isn't something that needs to be burdened onto the user.

If Debian uses cgroupv2 by default, why can't we?

2023-08-24 04:19 UTC, travispaul commented
I'm closing this PR as I've moved on to working on Debian 12. In the mean time, this branch works better than what's in master so I'll not delete it.

2023-08-24 04:19 UTC, closed without merging